Class test.testgit1 Extends Ens.BusinessService
{

Parameter ADAPTER = "Ens.InboundAdapter";

Method OnProcessInput(pInput As %RegisteredObject, Output pResponse As HS.Message.FHIR.Response) As %Status
{
	
		$$$LOGINFO("1111111111111111111111111111111111111111111111111111111111111111111111")
	
	//test git wafik test1
	
	//modif 2
	
   
		Quit 1
}






Class test.testgit1 Extends Ens.BusinessService
{

Parameter ADAPTER = "Ens.InboundAdapter";

Method OnProcessInput(pInput As %RegisteredObject, Output pResponse As HS.Message.FHIR.Response) As %Status
{
	
		$$$LOGINFO("1111111111111111111111111111111111111111111111111111111111111111111111")
	
	//test git wafik test1
	
	//modif 2
	
   
		Quit 1
}

}

}
